
version: "3.8"

services:
  pg_tileserv:
    container_name: pg_tileserv
    image: pramsey/pg_tileserv:20201211
    ports:
      - 7800
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - app_net
  varnish:
    container_name: varnish
    image: varnish:6.5.1
    ports:
      - ${PORT}:80
    volumes:
      - ./varnish/default.vcl/:/etc/varnish/default.vcl
    networks:
      - app_net
networks: 
  app_net: