
version: "3.9"

services:
  pg_tileserv:
    container_name: pg_tileserv
    image: pramsey/pg_tileserv:20201211
    ports:
      - 7800
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - app_net
  nginx:
    container_name: nginx
    image: nginx:1.19.6
    ports:
      - 8001:8001
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app_net
  varnish:
    container_name: varnish
    image: varnish:6.5.1
    ports:
      - 80
    volumes:
      - ./varnish/default.vcl/:/etc/varnish/default.vcl
    networks:
      - app_net
networks: 
  app_net: